### ISSUE TITLE
Exception on topic deletion

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#34]
Error message whereas the topic is really deleted.
<img width="156" alt="sans titre" src="https://cloud.githubusercontent.com/assets/597307/11663053/5855a93a-9dda-11e5-9bc7-d4bb740a6674.png">

**Comment by benel** [comment]
The problem doesn't occur all the time... More investigations are needed to identify the exact circumstances of this issue.

**Comment by Slaals** [comment]
Unfortunately I wasn't able to recreate this bug.

When you say "topic deletion" do you mean : 
- Deletion of a keyword, which will delete the topic from the item,
- Deletion of an analysis category

It's the only two ways I found to delete a topic, maybe I missed one...

**Comment by benel** [comment]
@Slaals Topic deletion is done through the viewpoint edition window (opened by clicking on `+` next to `Keywords`). Topic deletion is then done either by using the contextual menu or by selecting a topic and clicking the trash button.

**Comment by Slaals** [comment]
I tried different scenario, but no exception has been catched...

**Comment by benel** [comment]
Did you try it on your own argos server?

That could be related to authentication...

**Comment by benel** [comment]
Advanced viewpoint edition removed in v3.
