### ISSUE TITLE
First topic of an item mistakenly used as a name

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#35]
For no apparent reasons, when a new item is tagged with a topic, the topic name is also used as the name of the item.

While it could appear to be a good idea, it's not: a name is usually chosen to be _distinctive_ whereas a topic is supposed to be _reused_ for other items.

**Comment by Slaals** [comment]
It appears that this is done only when the item is tagged for the very first time. I tried this : 
- Tag an item (as the item has never been tagged, the tag name is used as the name of the item)
- Untag the item
- Rename the item to an empty name (which sets a default name such as "No name")
- Tag the item again

Following this procedure the item won't be renamed by the tag name. I think it could be a useful information. I'm working on it.

**Comment by Slaals** [comment]
When we tag an item, the program verifies if the item exists, if not, I creates it with the tag name!

You can find the line of code [here](https://github.com/Hypertopic/LaSuli/blob/master/content/js/lasuli.hypertopic.js#L731).

To stop this undesired effect, putting an empty parameter when calling `createItem` will keep the item name to default.

**Comment by benel** [comment]
Fixed in v3.
