### ISSUE TITLE
Duplicated value for an attribute

### ISSUE THREAD

**Issue by Slaals** [Hypertopic/LaSuli#39]
It appears that sometimes, when we add an attribute to an item the value is duplicated, moreover the system is then unable to remove this attribute.

It seems that the issue is related to the remote server. When I test this feature with my local server, this issue is vanished...

**Comment by benel** [comment]
Workaround
----------------

1. Edit the attribute to change the value.
2. Delete the attribute.

**Comment by benel** [comment]
Attribute edition removed in v3. Use Porphyry instead.
