### ISSUE TITLE
Check if the current page is annotated

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#44]
You may get the number of highlights as additional information.

Moreover, for privacy reasons, this should be done only on sites listed in the user's white list.

**Comment by benel** [comment]
> Au niveau de la création de la web extension, pourriez-vous me re-expliquer brièvement quels est le nombre à afficher sur l’icone de la web ext ?

C’est un choix de conception… On pourrait compter (au choix) :
- le nombre de thèmes et d’attributs associés,
- le nombre de points de vue, 
- le nombre de fragments.

Le but étant de montrer que la ressource a été plus ou moins « travaillée ».
Vu que la nouvelle version de LaSuli que vous développez ne permettra que le tagage de framents (et non de ressources entières), 
vu que l’une des plus grosses utilisations est IF14, avec un seul point de vue à uniquement trois thèmes (toujours les mêmes), 
je pense que ce qui est le plus pertinent pour évaluer le travail sur une ressource est le nombre de fragments.

**Comment by florentpergoud** [comment]
Ainsi il faut à partir de l'URL demander via les fonctions de hypertopic si la page est annotée ?
Avec ce genre de requête ?
```javascript
hypertopic.getView()
```
Il faudrait chercher via une URL la présence d'item ?

**Comment by benel** [comment]
Oui, c'est ça. Voici la spécification de la méthode qui dans l'API permet d'obtenir l'item à partir d'une ressource : 
 
https://github.com/Hypertopic/Protocol/blob/master/README.md#resource

**Comment by florentpergoud** [comment]
Je comptais donc utiliser 
```javascript
hypertopic.getView('/item/?resource=${URL}')
  .then(_log);
```
Cependant je ne peux accéder aux serveurs pour trouver des ressources à tester.
Vais-je dans la bonne direction ?
Pourriez-vous me fournir des accès ou un jeu de test ?

**Comment by benel** [comment]
> Cependant je ne peux accéder aux serveurs pour trouver des ressources à tester.

Si, si. Vous pouvez par exemple consulter [cet entretien](http://cassandre.hypertopic.org/text/MISS/e29902013074340b1b52155376000cf0). Il est surligné 12 fois.

**Comment by benel** [comment]
Et [voici un autre entretien](http://cassandre.hypertopic.org/text/enseignants-decrocheurs/deb51701fe5e555acf3a765a30115e04), encore plus annoté (et selon plusieurs points de vue).
