### ISSUE TITLE
Get details about a corpus viewpoint

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#46]
Contrary to v2 where listed viewpoints were user's ones. They will be based on the corpus. 
👍 Pros: No need to assign manually every student to the class viewpoint.
👎 Cons: IF14 corpus is HUGE. This will take time to load it.

Contrary to v2, because viewpoints names are not always well chosen, viewpoints will:
- display the number of related highlights in the current page,
- use the same color used for highlights in the page.

As in v2, once selected a viewpoint should display:
- its topics,
- its related fragments in the text (with a color for every different topic)
- its related fragments in the margin (beneath the topic).

**Comment by benel** [comment]
A few questions regarding highlight colors for you, @christophe-lejeune:

- Can we assume that 9 is a sufficient number for categories in most analyses (in a given viewpoint)?
- Here are 6 cycles of the same 9 colors, is there an order of highlighters that you would prefer to use?

<img width="923" alt="highlighters colors" src="https://user-images.githubusercontent.com/597307/32618833-1a97329e-c579-11e7-8bd8-94bdfdf40505.png">

The same colors will also be used in feature #45.

**Comment by benel** [comment]
> 👎 Cons: IF14 corpus is HUGE. This will take time to load it.

Not that huge. In JSON, it is 8600 records, 2.6 Mo. Downloading it from the same network takes 0.9s.

**Comment by christophe-lejeune** [comment]
Labelling a text consists in highlighting selected extracts and relating these extracts to a few words (the `label`, also known as the `code` or the `node`). In Hypertopic terms, the label is a topic. 

The label can either refers to properties (dimensions) or to a category. 
* It is very unlikely that a category requires more than 9 properties to be defined. 
* It is also unlikely than more than 9 categories are created inside one viewpoint. 

If colors are available and if different labels can have the same color, the user will certainly use the same color for all the properties defining one category. Different colors would then be used to identify labels referring to the  conditions or consequences related to the category at stake. 

So, nine different colors is definitely enough if more than 9 labels can be created. However prohibiting to create more than 9 labels/topics seems restrictive to me. We can thus live with it.

I have no particular preference between the featured cycles.

**Comment by gnoxr** [comment]
J'ai fait un petit peu de recherches pour le mélange des couleurs. Le W3C spécifie différents modes de [mélange de couleurs][blend], utilisés par tout ce qui lit CSS et/ou SVG, ainsi que par une [bibliothèque `npm`][npm-blend]. Une couleur est formée de trois composantes (R, G, B). Parmi les 16 modes de mélange défini, 15 ne nous intéressent pas :

- `normal` (pas de mélange)
- `hue`, `saturation`, `luminosity`, `color` prennent individuellement des composantes HSL d'une couleur ou de l'autre
- `difference` et `exclusion` soustraient une couleur à l'autre (effet négatif)
- `darken` renvoie les composantes les plus sombres
- `lighten` renvoie les composantes les plus claires
- `color-dodge` éclaircit une couleur pour avoir la luminosité de l'autre
- `color-burn` assombrit une couleur pour avoir la luminosité de l'autre
- `hard-light`, `soft-light`, `overlay` prennent en compte l'ordre des couleurs
- `screen` est un mélange éclaircissant (inutile car nos couleurs sont pâles)

Le seul qui nous intéresse en théorie est `multiply`, qui applique un mélange assombrissant. Il travaille à partir de couleurs suivant le modèle RGB.

La formule des 9 couleurs, basée sur la teinte, utilise le modèle HSL. Étant donné qu'il n'y a que 9 couleurs et qu'elles ne changeront pas, j'aurais proposé de les écrire "en dur", en RGB, plutôt que de les calculer dynamiquement dans le script. Si ça ne pose pas de problème, je teste cet algorithme.

[blend]: https://www.w3.org/TR/compositing-1/
[npm-blend]: https://www.npmjs.com/package/color-blend
