### ISSUE TITLE
Erase an highlight

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#52]

**Comment by benel** [comment]
@Franck Whereas it could be deleted from the text itself, it is probably far easier to do it from the sidebar (as it was done in LaSuli v2, with an icon next to the text of the fragment).

**Comment by franck-eyraud** [comment]
Removing a fragment is done in [this branch](https://github.com/franck-eyraud/LaSuli/tree/highlight)
As for #47, there is the issue how everything refreshes after change.
