### ISSUE TITLE
Highlights are not always shown in the page

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#60]
It seems:

- to work when the URI of the page is typed in the address bar,
- not to work, when the page is opened by clicking on the link from another page.

On a given session, if it works once, it seems to work after (it might be in a cache).

# Workaround

Press `R` (to reload) in the console.

**Comment by franck-eyraud** [comment]
It seems that the above fix (second one) solves the problem, let me know if you confirm. 

Not sure yet if it also solves #58, if not I have tested other changes that might fix it.

**Comment by benel** [comment]
> It seems that the above fix (second one) solves the problem, let me know if you confirm.

Sounds great! I'll test it.
