### ISSUE TITLE
User's viewpoints should be displayed.

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#64]
If only page's viewpoints are displayed, it is impossible to annotate a page in the first place.

**Comment by franck-eyraud** [comment]
Could you give an example to figure out the issue ?

**Comment by benel** [comment]
> Could you give an example to figure out the issue ?

I can. But the assignee is myself ;)

Let's suppose that Alice wants to annotate a new page.
Because the page is not already annotated, no viewpoints are displayed (with the current version). So she cannot start her analysis.

Instead, one way to begin with would be to display also the viewpoints she is registered to. Getting 
http://argos2.test.hypertopic.org/user/alice shows that she is registered to "Grille d'analyse du SI".
