### ISSUE TITLE
Pages that have never been highlighted before should be highlightable

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#66]
Reported by @khuloud84.

**Comment by benel** [comment]
@franck-eyraud In fact, when the item was found with `/item/?resource` on Argos+Cassandre but not found on Argos alone, it should be created on Argos (instead of printing an error to the console).

https://github.com/Hypertopic/LaSuli/commit/fe537948db3f149a7251de2eb86bf65578e572e4#diff-2b6e46436cc8167726516dc3bacdf6acR47

The solution should be very similar to what you did for Hypertopic/Porphyry#132.

**Comment by franck-eyraud** [comment]
Thank you for the fix. I wanted to have a look at it this afternoon, but you have been faster.

I have one comment about this situation : the catch call should create a new item only if the error was `404 Not found`. But it seems that there is now way to distinguish between the different kind of errors, and this comes from the library. Do you think there could be a way to return the HTTP code [here](https://github.com/Hypertopic/lib-node/blob/master/src/index.js#L26)  ?

**Comment by benel** [comment]
There are indeed related problems that are still not fixed, such as a 404 or 301 on `getViews` on `/item/?resource`.
As for another fixed part in the code (I don't remember where), HTTP errors on `getViews`  should not be handled as exceptions (since it is supposed to be broadcasted to a kind of P2P architecture, with no central control), they should be considered as an empty response.

**Comment by benel** [comment]
> As for another fixed part in the code (I don't remember where), HTTP errors on getViews should not be handled as exceptions (since it is supposed to be broadcasted to a kind of P2P architecture, with no central control), they should be considered as an empty response.

It was fixed in Hypertopic/lib-node 3.1.5 in commit [d9ca55](https://github.com/Hypertopic/lib-node/commit/d9ca553341d9ef3a9610dbfcf39962173a123923).
